### ISSUE TITLE
zuul转发上传服务接口失败，造成无法上传

### ISSUE THREAD

**Issue by mrjerryli** [slowboy666/Taroco#61]
上传服务upload-file-api自行创建脚手架子服务
在zuul配置中添加了如下的配置：
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
通过网关zuul调用上传服务，转发失败，造成无法上传，
后台控制台异常：Failed to parse multipart servlet request，
在网关调用接口之上添加/zuul/**，网关zuul绕过springMVC直接调用子服务，也是失败的，
请教您一下，希望可以关注解决一下。

**Comment by liuht777** [comment]
已解决 #62
